# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-25 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurblog', '0002_auto_20160616_1611'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newsentry',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='tease',
            field=models.TextField(),
        ),
    ]
