# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-27 16:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurblog', '0003_auto_20160625_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='jurblog.Category', verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='tease',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=b''),
        ),
    ]
